### ISSUE TITLE
Image cuts off early on short/power-less origins

### ISSUE THREAD

**Issue by JadeJuno** [Exzotic5485/origins-image-generator#1]
I was trying the website on the vanilla 10 Origins, and I saw that the Human origin just cuts off early. The border doesn't finish properly.

It's a small error though, I don't think it's too urgent to fix, but it's still there so :shrug:
![Human](https://github.com/user-attachments/assets/4e51bbe7-8159-4902-a435-91ffdd953d22)

**Comment by Exzotic5485** [comment]
Should be fixed now, thanks for reporting.
